### ISSUE TITLE
9.0 not working

### ISSUE THREAD

**Issue by Jeoleo7** [sonyxperiadev/device-sony-keyaki#23]
After executing make -j  4
===========================================
[1/1] out/soong/.minibootstrap/minibp out/soong/.bootstrap/build.ninja
[55/56] glob prebuilts/ndk/stl.bp
[77/77] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
out/build-aosp_g8232-cleanspec.ninja is missing, regenerating...
out/build-aosp_g8232.ninja is missing, regenerating...
[119/947] including device/sony/common/Android.mk ...
hardware/qcom/media/sdm845/mm-video-v4l2/vidc/venc/Android.mk:45: warning: "venc: PQ compiled out"
/bin/bash: line 0: pushd: out/target/product/keyaki/odm/: No such file or directory
[562/947] including system/sepolicy/Android.mk ...
system/sepolicy/Android.mk:79: warning: BOARD_SEPOLICY_VERS not specified, assuming current platform version
[947/947] including vendor/qcom/opensource/wlan/wcnss-service/Android.mk ...
build/make/core/Makefile:71: warning: Duplicate header copy: out/target/product/keyaki/obj/include/qcom/display/qd_utils.h
build/make/core/Makefile:71: warning: Defined in: hardware/qcom/display/sde/libqdutils/../common.mk hardware/qcom/display/sde/libqdutils/../common.mk
build/make/core/Makefile:28: warning: overriding commands for target `out/target/product/keyaki/system/vendor/etc/gps.conf'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `out/target/product/keyaki/system/vendor/etc/gps.conf'
[ 99% 723/724] glob frameworks/base/core/res/res/**/*
ninja: error: 'kernel/sony/msm-4.9/common-kernel/kernel-dtb-keyaki', needed by 'out/target/product/keyaki/kernel', missing and no known rule to make it
22:01:36 ninja failed with: exit status 1

**Comment by jerpelea** [comment]
the kernel images are not provided yet . Please use the script .sh to build them

**Comment by bartcubbins** [comment]
No longer relevant
